language: node_js
cache:
  directories:
    - ~/.npm
    - "node_modules"
script:
  - npm run test:single
notifications:
  email: false
node_js:
  - 'node'
  - '9'
  - '8'
  - '6'
  - '4'
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
